version: "3.8"

services:
  db:
    image: postgis/postgis:12-master
    container_name: mapnotes-flask-restful-db
    volumes:
      - ./sql/mapNotes.sql:/docker-entrypoint-initdb.d/mapNotes.sql
    environment:
      - POSTGRES_DB=mapnotes_api
      - POSTGRES_USER=mapnotes_api_user
      - POSTGRES_PASSWORD=password

  api:
    container_name: mapnotes-flask-restful-api
    build: .
    environment:
      - DB_HOST=${CONTAINER_DB_HOST}
      - DB_PORT=${CONTAINER_DB_PORT}
      - DB_NAME=${CONTAINER_DB_NAME}
      - DB_USER=${CONTAINER_DB_USER}
      - DB_PASSWORD=${CONTAINER_DB_PASSWORD}
    ports:
      - "5001:5000"
    depends_on:
      - "db"
    command: ["python", "app.py"]

networks:
  default:
    name: mapnotes_flask_app_test


