version: "3.8"

services:
  db:
    image: postgis/postgis:12-master
    container_name: mapnotes-flask-restful-db
    volumes:
      - ./sql/mapNotes.sql:/docker-entrypoint-initdb.d/mapNotes.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mapnotes_api
      - POSTGRES_USER=mapnotes_api_user
      - POSTGRES_PASSWORD=password

  api:
    container_name: mapnotes-flask-restful-api
    build: .
    environment:
      - DB_HOST=db
      - DB_NAME=mapnotes_api
      - DB_USER=mapnotes_api_user
      - DB_PASSWORD=password
      - DB_PORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]

  newman:
    image: postman/newman
    container_name: newman-api-tests
    depends_on:
      - "api"
    command:
      run postman_collection.json
      -e postman_environment.json
    volumes:
      - ./api/test:/etc/newman

