version: "3.8"

services:
  db:
    image: postgis/postgis:12-master
    container_name: mapnotes-flask-restful-db
    volumes:
      - ./sql/mapNotes.sql:/docker-entrypoint-initdb.d/mapNotes.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mapnotes_api
      - POSTGRES_USER=mapnotes_api_user
      - POSTGRES_PASSWORD=password

  api:
    container_name: mapnotes-flask-restful-api
    build: .
    environment:
      - DB_HOST=db
      - DB_NAME=mapnotes_api
      - DB_USER=mapnotes_api_user
      - DB_PASSWORD=password
      - DB_PORT=5432
    ports:
      - "8080:5000"
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:5432", "--", "flask", "run"]
    # command: ["python", "app.py"]

  newman:
    image: postman/newman
    container_name: newman-api-tests
    depends_on:
      - "api"
    # command: ["./etc/newman/wait-for-it.sh", "api:5000", "--", "run postman_collection.json -e postman_environment.json"]
      # run postman_collection.json
      # -e postman_environment.json
    command:
      run postman_collection.json
      -e postman_environment.json
      # -r html, cli
      # --reporter-html-export reports/api_postman_test_run.html
      # --reporter-html-template reports/customTemplate.hbs
    volumes:
      - ./api/test:/etc/newman

