openapi: 3.0.0
info:
  title: MapNotes api
  description: Save and query MapNotes for the Zika Client
  contact:
    email: michael.joyce@illiniarts.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: '1.0'

components:
  schemas:
    mapNotePostBody:
      properties:
        title:
          type: string
        body:
          type: string
    mapNote:
      properties:
        id:
          type: integer
        title:
          type: string
        body:
          type: string
    arrayOfMapNotes:
        type: array
        items:
          $ref: '#/components/schemas/mapNote'
    featureCollection:
      # $ref: 'https://geojson.org'
      description: GEOJSON Feature Collection
      properties:
        type:
          type: string
          example: 'Feature Collection'
        features:
          type: object
    feature:
      description: GEOJSON Feature

paths:
  /notes:
    get:
      summary: Returns a list of all MapNotes
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/arrayOfMapNotes'
    post:
      summary: Add a new MapNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mapNotePostBody'
      responses:
        '201':
          description: Created
        '400':
          description: Cannot add note, title cannot be null
  
  /notes/{note_id}:
    parameters:
      - in: path
        name: note_id
        required: true
        schema:
          type: integer
          minimum: 1
        description: The MapNote ID
    get:
      summary: Returns a MapNote
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mapNote'
        '404':
          description: MapNote not found
    delete:
      summary: Remove a MapNote
      responses:
        '204':
          description: MapNote deleted
        '404':
          description: MapNote not found
  
  /notes/{note_id}/features:
    parameters:
      - in: path
        name: note_id
        required: true
        schema:
          type: integer
          minimum: 1
        description: The MapNote ID
    get:
      summary: Returns a MapNote's FeatureCollection
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/featureCollection'

        '404':
          description: MapNote not found
    put:
      summary: Adds (or replaces) a FeatureCollection to a MapNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/featureCollection'
      responses:
        '201':
          description: Created
        '404':
          description: MapNote not found

externalDocs:
  description: GeoJSON Documentation
  url: https://geojson.org/

